### ISSUE TITLE
throws an error when comes to several selectors

### ISSUE THREAD

**Issue by kalinichenko** [totora0155/postcss-namespace#7]
.trip,
  .trip-disabled {
    background-color: #eaeaea;
  }

Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property '0' of null
at getFirst (/.../node_modules/postcss-namespace/index.js:18:45)

**Comment by totora0155** [comment]
omg:fearful:

I don't know well, maybe.
If you like, please give a little more wide info? (code)

---

``` css
@prefix namespace;

.trip,
.trip-disabled {
  background-color: #eaeaea;
}

/*
.namespace-trip,
.namespace-trip-disabled {
  background-color: #eaeaea;
}
*/
```
